### ISSUE TITLE
Release version 5 not supported

### ISSUE THREAD

**Issue by khurshedkadyrov** [khurshedkadyrov/googleProject#1]

**Comment by ydanylchenko** [comment]
@khurshedkadyrov It's not fixed in this repostiory

**Comment by ydanylchenko** [comment]
@khurshedkadyrov  https://github.com/khurshedkadyrov/googleProject/issues/3 should be addressed first

**Comment by khurshedkadyrov** [comment]
what do u mean by version 5? is it java 1.5 that we had to change to version 8 in compile?

**Comment by khurshedkadyrov** [comment]
File | Settings | Build, Execution, Deployment | Compiler | Java Compiler

**Comment by khurshedkadyrov** [comment]
![2019-10-21-19-09-25](https://user-images.githubusercontent.com/56610066/67249706-a1b64880-f436-11e9-9ab0-d9ab1c140a94.png)

**Comment by khurshedkadyrov** [comment]
fixed and added to day3 branch @gogr

**Comment by ydanylchenko** [comment]
gj
