### ISSUE TITLE
missing POM.xml

### ISSUE THREAD

**Issue by ydanylchenko** [khurshedkadyrov/googleProject#3]
@khurshedkadyrov pom.xml is not committed to this repository

**Comment by khurshedkadyrov** [comment]
> @khurshedkadyrov pom.xml is not committed to this repository

if  i only knew how to commit POM

**Comment by ydanylchenko** [comment]
@khurshedkadyrov  In the same way as you committed all the other files
http://somup.com/cq6r3pfc2F

**Comment by khurshedkadyrov** [comment]
POM is added to both master and  day3 branches

**Comment by ydanylchenko** [comment]
@khurshedkadyrov  Why the file name is "POM"? It's supposed to be "POM.xml".

**Comment by khurshedkadyrov** [comment]
> @khurshedkadyrov Why the file name is "POM"? It's supposed to be "POM.xml".

Changed to pom.xml boss #3 @gogr

**Comment by ydanylchenko** [comment]
@khurshedkadyrov One more thing, could you please remove the pom.xlm file

**Comment by khurshedkadyrov** [comment]
> @khurshedkadyrov One more thing, could you please remove the pom.xlm file

removed @gogr
